when:
  event: push
  branch: main

steps:
  build:
    image: rust:latest
    commands:
      - apt-get update
      - apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev rustup build-essential curl wget file libssl-dev
      - rustup toolchain install nightly
      - rustup target add wasm32-unknown-unknown
      - cargo install trunk tauri-cli
      - cargo tauri build
      - mv target/release/bundle/deb/fabseapp_0.0.0_amd64.deb fabseapp_0.0.0_amd64.deb
      - mv target/release/bundle/appimage/fabseapp_0.0.0_amd64.AppImage fabseapp_0.0.0_amd64.AppImage

  release:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      file_exists: overwrite
      files:
        - "fabseapp_0.0.0_amd64.deb"
        - "fabseapp_0.0.0_amd64.AppImage"
      checksum: sha256
      api_key:
        from_secret: FABSEGIT_RELEASE
      target: master
      title: Fabseapp ${CI_COMMIT_TAG} 
      draft: true
